### ISSUE TITLE
How to enable google genomics API as a service account

### ISSUE THREAD

**Issue by vangalamaheshh** [googlegenomics/dockerflow#14]
Hello -

I am trying to run dockerflow linear graph example and have got following error:
<error>
Exception in thread "main" com.google.cloud.dataflow.sdk.Pipeline$PipelineExecutionException: com.google.cloud.genomics.dockerflow.runner.TaskException: Error starting Docker task stepOne. Cause: HTTP error: 401 for url https://genomics.googleapis.com/v1alpha2/pipelines:run{
  "error": {
    "code": 401,
    "message": "The request does not have valid authentication credentials.",
    "status": "UNAUTHENTICATED"
  }
}
</error>

I have enabled cloud storage, data flow, google genomics APIs for the project at hand. 
I have also added GOOGLE_APPLICATION_CREDENTIALS=<my-keys.json>
Let me know how to fix this error?
Thanks.

- Mahesh

**Comment by jbingham** [comment]
Try running gcloud auth login again and that should fix it for you.
Dockerflow users application default credentials via the standard Google
APIs method. The credentials json file isn't looked for or used, afaik .

Cheers,
Jonathan

**Comment by vangalamaheshh** [comment]
Hi Jonathan -

Thanks for your reply.
I have to mention that I am trying dockerflow in a docker container.
Long story short, what I'm trying to accomplish (this is a personal project) is to have a docker container with workflows that use dockerflow to run on GCP.
Please take a look at my dockerfile https://github.com/vangalamaheshh/dockerfiles/blob/master/bib/Dockerfile

I am wondering if DirectPipelineRunner supports this. Also, I did,

gcloud auth application-default login and successfully had the credentials saved to a json file.

However, I am still getting the same error that I pasted above.
Please let me know what you think.
Thanks much.

- Mahesh

**Comment by jbingham** [comment]
Hmm. Your auth is messed up somehow. Run Dockerflow with --help and it will
print out your access token. Then, from a previous question on github, I
replied:


Dockerflow uses an access token for API calls and GCS access. You can test
that it works with a GCS bucket you have access to, like this:

curl https://storage.googleapis.com/MY-BUCKET/MY-PATH?access_token=MY-TOKEN

where MY-BUCKET/MY-PATH is the GCS path (without the gs:// prefix) and
MY-TOKEN is obtained with the code above.

Once you're able to use the token to access your bucket, it should be
working. If not, you need to gcloud auth login again, making sure you're
logging into the right project. This all has nothing to do with Dockerflow.
It's standard Google Cloud auth.

On your bigger goal:

Do you want to orchestrate and monitor the workflow using Cloud Dataflow?
If yes, then you absolutely should be able to put Dockerflow inside a
Docker container. You would use the default DataflowPipelineRunner.

Note that I'm not sure what the benefit of this is vs launching the
Dockerflow workflow from your laptop. With the default runner, Dockerflow
submits the whole workflow to GCP to execute. You can exit the shell after
it's started and check back from a different computer.

If you want to run *without* Cloud Dataflow and the monitoring UI, you
would use the DirectPipelineRunner. That should also be possible from
within a Docker container.

Note that Dockerflow launches new VMs to execute the actual tasks. The
runner is just an orchestrator. Dockerflow tasks do not run on the same VM
as Dockerflow itself.

Cheers,
Jonathan

**Comment by vangalamaheshh** [comment]
Hi Jonathan -

I still have issues in running dockerflow.
Here is what I have done,

1) I logged in into docker container with dockerflow and google cloud SDK installed
2) gcloud init
3) Selected "project", "compute zone"
4) Verification code

Here is the gcloud auth list output:

gcloud auth list
Credentialed Accounts:
 - <MYEMAIL> ACTIVE

and gcloud config list output:

Your active configuration is: [default]

[compute]
region = us-east1
zone = us-east1-b
[core]
account = <MYEMAIL>
disable_usage_reporting = True
project = bioinformatics-in-browser

However, running dockeflow --help errors out with,

Exception in thread "main" java.io.IOException: The Application Default Credentials are not available. They are available if running on Google App Engine, Google Compute Engine, or Google Cloud Shell. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
        at com.google.api.client.googleapis.auth.oauth2.DefaultCredentialProvider.getDefaultCredential(DefaultCredentialProvider.java:98)
        at com.google.api.client.googleapis.auth.oauth2.GoogleCredential.getApplicationDefault(GoogleCredential.java:213)
        at com.google.api.client.googleapis.auth.oauth2.GoogleCredential.getApplicationDefault(GoogleCredential.java:191)
        at com.google.cloud.genomics.dockerflow.Dockerflow.main(Dockerflow.java:128)


Let me know your thoughts.
Thanks much.

- Mahesh

**Comment by vangalamaheshh** [comment]
Also, if you want to replicate this issue, please

1) docker pull mvangala/bib:0.0.1
2) docker run --name dockerflow_test -it mvangala/bib:0.0.1 bash

Let me know if you could launch dockerflow examples from with in the container?
Thanks much for your time and efforts with this, Jonathan.

Regards,
Mahesh

**Comment by vangalamaheshh** [comment]
Jonathan -

So, seems like following specific steps such as,

1) export GOOGLE_APPLICATION_CREDENTIALS=Keys.json
2) gcloud auth application-default login
3) unset GOOGLE_APPLICATION_CREDENTIALS
4) dockerflow run example

did the trick.

Thank you.

- Mahesh

**Comment by jbingham** [comment]
Hmm. Could be something about gcloud inside of Docker, and the Google API
for auth not working well with it.

Are you able to run Dockerflow now from your shell prompt and from the VM
directly?
